### ISSUE TITLE
Index out of bounds in nn::gnnb

### ISSUE THREAD

**Issue by mrp089** [SimVascular/svFSIplus#186] opened 2024-02-15 05:09 UTC
### Description

I have two identical meshes: one original mesh (`fluid_good.vtu`) and one manipulated with VTK slightly displaced nodes (`fluid_bad.vtu`). Everything else should be the same, but `fluid_bad.vtu` causes a heap corruption error. After some debugging, I found that this line tries to write out of bounds:
https://github.com/SimVascular/svFSIplus/blob/b2153cf6dd9deaa8c1cccd81b58e37013deb3324/Code/Source/svFSI/nn.cpp#L601

### Reproduction

Run [this fluid simulation](https://github.com/SimVascular/svFSIplus/files/14291701/malloc.zip). It should crash quickly.

### Expected behavior

Here's the output with the good mesh (debug + indices `a` and `b`):
```
[gnnb:0] e: 1
[gnnb:0] g: 1
[gnnb:0] nsd: 3
[gnnb:0] insd: 2
[gnnb:0] eNoNb: 4
[gnnb:0] iM: 1
[gnnb:0] Ec: 2144
[gnnb:0] eNoN: 8
[gnnb:0] msh.IEN.nrows: 8
[gnnb:0] msh.IEN.ncols: 6400
a b
4 4
5 5
6 6
7 7
```

And here is the bad one:
```
[gnnb:0] e: 1
[gnnb:0] g: 1
[gnnb:0] nsd: 3
[gnnb:0] insd: 2
[gnnb:0] eNoNb: 4
[gnnb:0] iM: 1
[gnnb:0] Ec: 1
[gnnb:0] eNoN: 8
[gnnb:0] msh.IEN.nrows: 8
[gnnb:0] msh.IEN.ncols: 6400
a b
4 0
5 1
6 2
7 3
8 5
```
It causes the error `Index i=8 is out of bounds for 8 vector`.

### Additional context

This is on an M2 Max with macOS Sonoma 14.2.1.

@ktbolt, can you look at this? I have no idea what these functions do and what might be offending them. Thank you!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by ktbolt** [comment] 2024-02-15 07:33
The problem is that I implemented the check https://github.com/SimVascular/svFSIplus/blob/b2153cf6dd9deaa8c1cccd81b58e37013deb3324/Code/Source/svFSI/nn.cpp#L589

incorrectly from the Fortran. In Fortran the do-loop variable `b` will be `eNoN+1` if the loop exits without finding a node match, the C++ for-loops don't work this way so I need to set a bool if a node is found and check that.

I am guessing that you are seeing this problem because your face node IDs are wrong somehow, maybe the IDs are off by 1.

**Comment by ktbolt** [comment] 2024-02-15 18:19
I've fixed the node matching error and also added a more informative error message
```
[svFSIplus::gnnb] The 'f_interface' face node 0 could not be matched to a node in the 'fluid' volume mesh.
```

**Comment by mrp089** [comment] 2024-02-15 19:00
Thank you for the quick fix, @ktbolt!

Can you look at the mesh and see why `fluid_bad.vtu` is throwing this error and `fluid_good.vtu` is not? The arrays `GlobalNodeID` and `GlobalElementID` should be identical. I also compared the `vtu` headers and it looks like the contain the same information, with the only difference being the `min`, `max`, and `offset` tags.

**Comment by ktbolt** [comment] 2024-02-15 21:11
Some of the nodes in`f_interface.vtp`  don't match any of the volume nodes in `fluid_bad.vtu` 
```
[check_nodes] Node ID: 1925
[check_nodes]   Face point: [0.647, 0.0, 0.0]
[check_nodes]   Vol  point: [0.6474944205265499, 9.916768200430095e-12, 1.5605716979035928e-13]
[check_nodes] Surface node IDs don't match volume. d: 0.0004944205265499103
```

**Comment by zasexton** [comment] 2024-02-15 22:25
This is likely from the hash maps used to initialize the problem. The assumption is that the boundary surface nodes are drawn exactly from a set of nodes in the volume mesh. If this is not the case, the problem will be unable to assign the boundary conditions. I will look into amending this now

**Comment by ktbolt** [comment] 2024-02-15 22:56
@zasexton Good, was wondering why this error was not caught during initialization.

**Comment by zasexton** [comment] 2024-02-16 02:53
and just to make sure that I am reproducing this correctly. The following failure of convergence is the issue observed when using the `fluid_bad.vtu` for this problem, correct?
```bash
---------------------------------------------------------------------
 Eq     N-i     T       dB  Ri/R1   Ri/R0    R/Ri     lsIt   dB  %t
---------------------------------------------------------------------
 NS 1-1  5.629e+02  [-2147483648  nan  nan  nan]  !251000 -2147483648 100!
 ```
 and @ktbolt we included a check for duplicate nodes or duplicate elements in the hash map generation but did not include a check that the nodes within the surface.vtp files map exactly to nodes in the mesh files. This check will be added.

**Comment by mrp089** [comment] 2024-02-16 03:42
The error should be immediately:
```
[svFSIplus::gnnb] The 'f_interface' face node 0 could not be matched to a node in the 'fluid' volume mesh.
```
The mesh nodes don't quite match but should be identifiable with GlobalNodeID. I realize that this might be a unique application, trying to match faces and volume with non-conforming nodes but matching IDs. If it's not too much trouble, we could have the old matching as a default in case GlobalNodeID is given?

(The linear solver might not work well since I was using PETSc and changed it to FSILS to share it.)

**Comment by zasexton** [comment] 2024-02-16 03:47
Yes, I have created a branch for exactly this. Though when I ran the test problem on the main branch I was not getting the `svFSIplus::gnnb` error that you listed above.

**Comment by mrp089** [comment] 2024-02-16 03:49
Are you sure you are on the main branch at 0590d9ad99a67940d1c0dc980b9fe967523487de?

**Comment by zasexton** [comment] 2024-02-16 03:58
I'll double check now

**Comment by zasexton** [comment] 2024-02-16 04:02
```
commit b2153cf6dd9deaa8c1cccd81b58e37013deb3324 (HEAD -> main, origin/main, origin/HEAD)
Author: Dave Parker <dvdpax@gmail.com>
Date:   Wed Feb 14 10:44:19 2024 -0800

    Fix indexing off by 1. (#185)
```
this is the last commit to the main branch. It seems mine must be one behind.

**Comment by zasexton** [comment] 2024-02-16 04:17
Okay perfect I'm reproducing this error. 
```
[svFSIplus::gnnb] The 'f_interface' face node 0 could not be matched to a node in the 'fluid' volume mesh.
```

**Comment by zasexton** [comment] 2024-02-16 08:34
I have removed the hash maps as the default and rely on the `GlobalNodeID` and `GlobalElementID` assignments (hash maps are only called if the `face.gN` and `face.gE` are unassigned and have zero-sized vectors). However, this produced the following errors for both the `fluid_bad.vtu` and `fluid_good.vtu` :

```
[svFSIplus::gnnb] The 'f_interface' face node 0 could not be matched to a node in the 'fluid' volume mesh.
```

When I make copies of the surface meshes that remove the "GlobalNodeID" fields (thus forcing svFSI+ to utilitze the original hash map approach) we recover the ability to simulate the `fluid_good.vtu`. 
```
[WARNING] No node IDs found in the 'mesh_tube_fsi/fluid/mesh-surfaces/interface_noid.vtp' face file.Creating face node IDs using hash maps.
[WARNING] No node IDs found in the 'mesh_tube_fsi/fluid/mesh-surfaces/start_noid.vtp' face file.Creating face node IDs using hash maps.
[WARNING] No node IDs found in the 'mesh_tube_fsi/fluid/mesh-surfaces/end_noid.vtp' face file.Creating face node IDs using hash maps.
---------------------------------------------------------------------
 Eq     N-i     T       dB  Ri/R1   Ri/R0    R/Ri     lsIt   dB  %t
---------------------------------------------------------------------
 NS 1-1  4.790e-01  [0 1.000e+00 1.000e+00 9.991e-02]  [63 -23 50]
 NS 1-2  7.560e-01  [7 2.401e+00 2.401e+00 9.478e-02]  [18 -24 17]
 NS 1-3  1.184e+00  [-6 4.651e-01 4.651e-01 9.996e-02]  [56 -23 48]
 NS 1-4  1.509e+00  [-1 8.433e-01 8.433e-01 9.488e-02]  [32 -24 28]
 NS 1-5  4.894e+00  [-12 2.440e-01 2.440e-01 9.990e-02]  [364 -2 93]
 NS 1-6  5.711e+00  [-15 1.644e-01 1.644e-01 9.967e-02]  [110 -23 72]
 NS 1-7  8.528e+00  [-21 8.529e-02 8.529e-02 9.948e-02]  [271 -1 92]
 NS 1-8  9.389e+00  [-32 2.355e-02 2.355e-02 9.917e-02]  [115 -23 74]
 NS 1-9  1.141e+01  [-45 5.334e-03 5.334e-03 9.915e-02]  [208 -23 89]
 NS 1-10s 1.377e+01  [-64 6.298e-04 6.298e-04 9.836e-02]  [226 -23 89]
 NS 2-1  1.435e+01  [0 1.000e+00 5.001e-01 9.827e-02]  [64 -23 43]
 NS 2-2  1.459e+01  [-2 7.403e-01 3.702e-01 9.756e-02]  [11 -23 10]
 NS 2-3  1.767e+01  [-17 1.364e-01 6.822e-02 9.999e-02]  [323 -3 93]
 NS 2-4  2.101e+01  [-32 2.287e-02 1.144e-02 9.990e-02]  [346 -7 93]
 NS 2-5  2.300e+01  [-49 3.545e-03 1.773e-03 9.823e-02]  [203 -23 89]
 NS 2-6  2.528e+01  [-68 3.776e-04 1.888e-04 9.853e-02]  [217 -23 88]
 NS 2-7  2.815e+01  [-88 3.713e-05 1.857e-05 9.873e-02]  [264 -2 92]
 NS 2-8  3.093e+01  [-108 3.668e-06 1.834e-06 9.841e-02]  [267 -3 92]
 NS 2-9s 3.386e+01  [-128 3.611e-07 1.806e-07 9.997e-02]  [266 -2 91]
 NS 3-1  3.444e+01  [0 1.000e+00 2.498e-01 9.861e-02]  [64 -23 43]
 NS 3-2  3.474e+01  [-3 6.623e-01 1.654e-01 9.826e-02]  [28 -23 26]
 NS 3-3  3.695e+01  [-15 1.681e-01 4.199e-02 9.990e-02]  [220 -23 90]
 NS 3-4  3.931e+01  [-31 2.706e-02 6.760e-03 9.929e-02]  [228 -23 90]
 NS 3-5  4.078e+01  [-47 4.167e-03 1.041e-03 9.990e-02]  [170 -23 85]
 NS 3-6  4.241e+01  [-67 4.157e-04 1.038e-04 9.959e-02]  [181 -23 86]
 NS 3-7  4.453e+01  [-87 4.143e-05 1.035e-05 9.979e-02]  [213 -23 90]
 NS 3-8  4.691e+01  [-107 4.134e-06 1.033e-06 9.920e-02]  [230 -23 91]
 NS 3-9s 4.975e+01  [-127 4.104e-07 1.025e-07 9.979e-02]  [253 0 91]
 NS 4-1  5.034e+01  [0 1.000e+00 1.249e-01 9.833e-02]  [64 -23 42]
 NS 4-2  5.197e+01  [-13 2.188e-01 2.732e-02 9.962e-02]  [181 -23 86]
 NS 4-3  5.457e+01  [-28 3.785e-02 4.727e-03 9.905e-02]  [241 -23 91]
 NS 4-4  5.611e+01  [-47 4.021e-03 5.021e-04 9.935e-02]  [174 -23 85]
 NS 4-5  5.817e+01  [-67 4.007e-04 5.004e-05 9.759e-02]  [207 -23 89]
 NS 4-6  6.096e+01  [-88 3.900e-05 4.870e-06 9.954e-02]  [249 -23 91]
 NS 4-7s 6.404e+01  [-108 3.881e-06 4.847e-07 9.943e-02]  [274 -3 92]
 NS 5-1  6.463e+01  [0 1.000e+00 6.239e-02 9.838e-02]  [64 -23 42]
 NS 5-2  6.650e+01  [-14 1.863e-01 1.162e-02 9.904e-02]  [197 -23 88]
 NS 5-3  6.843e+01  [-29 3.349e-02 2.089e-03 9.841e-02]  [201 -23 89]
 NS 5-4  7.054e+01  [-49 3.511e-03 2.190e-04 9.704e-02]  [212 -23 89]
 NS 5-5  7.285e+01  [-69 3.393e-04 2.117e-05 9.930e-02]  [224 -23 90]
 NS 5-6  7.568e+01  [-89 3.371e-05 2.103e-06 9.969e-02]  [264 -2 92]
 NS 5-7s 7.855e+01  [-109 3.360e-06 2.096e-07 9.936e-02]  [264 -2 91]
 NS 6-1  7.915e+01  [0 1.000e+00 3.117e-02 9.824e-02]  [64 -23 43]
 NS 6-2  8.116e+01  [-19 1.048e-01 3.267e-03 9.973e-02]  [205 -23 89]
 NS 6-3  8.349e+01  [-39 1.062e-02 3.311e-04 9.744e-02]  [224 -23 90]
 NS 6-4  8.552e+01  [-59 1.030e-03 3.211e-05 9.933e-02]  [200 -23 89]
 NS 6-5  8.851e+01  [-79 1.023e-04 3.189e-06 9.960e-02]  [295 -4 91]
 NS 6-6s 9.131e+01  [-99 1.019e-05 3.176e-07 9.928e-02]  [255 -1 91]
 NS 7-1  9.190e+01  [0 1.000e+00 1.557e-02 9.817e-02]  [64 -23 43]
 NS 7-2  9.393e+01  [-19 1.072e-01 1.669e-03 9.793e-02]  [205 -23 89]
 NS 7-3  9.637e+01  [-39 1.081e-02 1.683e-04 9.709e-02]  [226 -23 91]
 NS 7-4  9.888e+01  [-59 1.052e-03 1.638e-05 9.978e-02]  [231 -23 91]
 NS 7-5  1.017e+02  [-79 1.050e-04 1.635e-06 9.872e-02]  [254 0 92]
 NS 7-6s 1.046e+02  [-99 1.037e-05 1.614e-07 9.976e-02]  [265 -2 90]
 NS 8-1  1.052e+02  [0 1.000e+00 7.776e-03 9.805e-02]  [64 -23 43]
 NS 8-2  1.072e+02  [-20 9.720e-02 7.558e-04 9.950e-02]  [204 -23 89]
 NS 8-3  1.095e+02  [-40 9.768e-03 7.596e-05 9.848e-02]  [225 -23 90]
 NS 8-4  1.119e+02  [-60 9.623e-04 7.483e-06 9.996e-02]  [231 -23 91]
 NS 8-5s 1.148e+02  [-80 9.617e-05 7.479e-07 9.853e-02]  [251 -23 91]
 NS 9-1  1.154e+02  [0 1.000e+00 3.883e-03 9.988e-02]  [63 -23 43]
 NS 9-2  1.173e+02  [-19 1.010e-01 3.922e-04 9.928e-02]  [204 -23 89]
 NS 9-3  1.197e+02  [-39 1.000e-02 3.884e-05 9.807e-02]  [227 -23 91]
 NS 9-4  1.221e+02  [-60 9.814e-04 3.811e-06 9.773e-02]  [233 -23 91]
 NS 9-5s 1.249e+02  [-80 9.592e-05 3.725e-07 1.000e-01]  [255 -1 91]
 NS 10-1  1.255e+02  [0 1.000e+00 1.939e-03 9.975e-02]  [63 -23 42]
 NS 10-2  1.275e+02  [-20 9.938e-02 1.927e-04 9.902e-02]  [205 -23 89]
 NS 10-3  1.298e+02  [-40 9.855e-03 1.911e-05 9.784e-02]  [227 -23 90]
 NS 10-4  1.323e+02  [-60 9.642e-04 1.869e-06 9.774e-02]  [232 -23 91]
 NS 10-5s 1.351e+02  [-80 9.424e-05 1.827e-07 9.838e-02]  [254 0 91]
 ```
I agree that the hash map approach may be better suited if `GlobalNodeID` and `GlobalElementID` are explicitly not given; however, I think there might be another indexing error that is going on here? This may be related to the off-by-one indexing between the face and mesh data.

**Comment by zasexton** [comment] 2024-02-16 09:04
For reference, when we try running the `fluid_bad.vtu` with the surface meshes that do not have `GlobalNodeID` arrays (thus using the hash map approach) the new correctly caught error reads:
```
[WARNING] No node IDs found in the 'mesh_tube_fsi/fluid/mesh-surfaces/interface_noid.vtp' face file.Creating face node IDs using hash maps.
terminate called after throwing an instance of 'std::runtime_error'
  what():  The face node does not exist in the mesh.
```
This adds better error catching since the displaced fluid mesh will not have nodes that exactly match the `interface.vtp`, `start.vtp`, and `end.vtp` surface meshes. Thus **_we should require this scenario to throw an error_** since the user does not supply a known connectivity through `GlobalNodeID` arrays And the nodes are not guaranteed to match.

**Comment by ktbolt** [comment] 2024-08-24 00:24
This fix seems to be merged.

**Closed by ktbolt** 2024-08-24 00:24 UTC
Labels: bug
